import assert from 'node:assert/strict';
import {initial,stateSchema,workoutSchema,weekStart} from '../lib/data.ts';
import {legacyStarterPlan,strengthVersions,updatedFlexiblePlan,upgradeStarterPlan,upsertWorkout,canResume,previousDate,replacement} from '../lib/training.ts';
const fixture={id:'hybrid-record',date:'2026-09-20',name:'Strength · Gym + home',sessionId:'A',planName:initial.plan.name,status:'partial',minutes:12,effort:5,notes:'Gym first',sets:[{exercise:'Flat dumbbell bench press',reps:10,unit:'reps',incline:0,rest:90,weight:8,location:'Gym'}],distance:0,seconds:0,splits:[],runType:'none',pushups:null,situps:null,testType:'none',continuation:{session:strengthVersions.find(s=>s.variant==='Hybrid'),nextStep:4,skipped:false}};
assert.ok(workoutSchema.safeParse(fixture).success);
assert.ok(canResume(fixture));
const parsed=stateSchema.parse({...initial,workouts:[fixture]});
assert.equal(parsed.workouts[0].sets[0].weight,8);
assert.equal(parsed.workouts[0].continuation.nextStep,4);
assert.equal(parsed.workouts[0].continuation.session.variant,'Hybrid');
const resumed={...fixture,status:'complete',continuation:undefined,sets:[...fixture.sets,{exercise:'Incline push-up',reps:9,unit:'reps',incline:80,rest:90,location:'Home'}]};
const updated=upsertWorkout([fixture],resumed);
assert.equal(updated.length,1);assert.equal(updated[0].sets.length,2);assert.equal(canResume(updated[0]),false);
assert.equal(updated[0].date,'2026-09-20');
const dated=upsertWorkout([{...resumed,id:'other',date:'2026-09-21'}],resumed);
assert.deepEqual(dated.map(w=>w.date),['2026-09-21','2026-09-20']);
assert.equal(dated.filter(w=>w.date>=weekStart('2026-09-27')).length,1);
assert.equal(upsertWorkout(dated,{...resumed,date:'2026-09-22'}).length,2);
assert.equal(previousDate('2026-09-01'),'2026-08-31');assert.equal(previousDate('2026-01-01'),'2025-12-31');
assert.ok(strengthVersions.every(s=>s.id==='A'));
assert.equal(new Set(strengthVersions.map(s=>s.variant)).size,4);
assert.equal(updatedFlexiblePlan(updatedFlexiblePlan(initial.plan)).notes,initial.plan.notes);
assert.equal(upgradeStarterPlan(initial),initial);
const custom={...initial,plan:{...initial.plan,name:'My custom plan',notes:''}};
assert.equal(upgradeStarterPlan(custom),custom);
const legacyWorkout=structuredClone(fixture);delete legacyWorkout.continuation;delete legacyWorkout.sets[0].weight;delete legacyWorkout.sets[0].location;
assert.ok(workoutSchema.safeParse(legacyWorkout).success);
const swapped=replacement(strengthVersions[1].items[1],'Machine chest press');assert.equal(swapped.focus,'press');assert.equal(swapped.location,'Gym');
assert.equal(workoutSchema.safeParse({...fixture,sets:[{...fixture.sets[0],weight:-1}]}).success,false);
console.log('Training checks passed: backward compatibility, resume round-trip, same-record edits, dates/week boundaries, versions and substitutions.');

const old={...initial,plan:structuredClone(legacyStarterPlan),workouts:[fixture]};
const migrated=upgradeStarterPlan(stateSchema.parse(old));
assert.equal(migrated.planHistory.length,1);assert.deepEqual(migrated.planHistory[0].plan,old.plan);assert.deepEqual(migrated.workouts,old.workouts);
assert.equal(migrated.plan.sessions.find(s=>s.id==='C').items.length,3);
assert.equal(upgradeStarterPlan(migrated),migrated);
const edited=structuredClone(old);edited.plan.sessions[2].items[0].target='My custom warm-up';
assert.equal(upgradeStarterPlan(edited),edited);
