'use client';
import {useEffect,useRef,useState} from 'react';
import {Play,Pause,Flag,Upload,Volume2,Footprints} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {time} from '@/lib/data';
import {advance,finishLap,freshInterval,intervalSchema,parseSplits,startLap,stopEarly,togglePause,type IntervalState} from '@/lib/intervals';
const CACHE='stride-interval-draft-v1';
const uid=()=>crypto.randomUUID?.()??Array.from(crypto.getRandomValues(new Uint8Array(16))).map(v=>v.toString(16).padStart(2,'0')).join('');
export type IntervalResult={id:string,rounds:number,metres:number,splits:number[],recoveries:number[],duration:number,date:number,source:string};
export default function IntervalRunner({open,onClose,onReview,canSave}:{open:boolean,onClose:()=>void,onReview:(r:IntervalResult)=>void,canSave:boolean}){
 const [s,setS]=useState<IntervalState>(()=>freshInterval('')),[now,setNow]=useState(0),[hydrated,setHydrated]=useState(false),[mode,setMode]=useState('stopwatch'),[confirm,setConfirm]=useState(false),[err,setErr]=useState(''),[manual,setManual]=useState(''),[cumulative,setCumulative]=useState(false),[imported,setImported]=useState<number[]|null>(null),[awake,setAwake]=useState(false),[importMetres,setImportMetres]=useState(400),[importRest,setImportRest]=useState(120);
 const current=useRef(s),audio=useRef<AudioContext|null>(null),cueKey=useRef(''),openRef=useRef(open);openRef.current=open;
 const commit=(next:IntervalState)=>{current.current=next;setS(next)};
 useEffect(()=>{try{const raw=localStorage.getItem(CACHE);if(raw){const p=intervalSchema.parse(JSON.parse(raw));commit(p.phase==='rest'?{...p,phase:'ready',paused:0}:p.phase==='run'?{...p,paused:p.paused||Date.now()}:p)}else commit(freshInterval(uid()));}catch{commit(freshInterval(uid()))}setHydrated(true);setNow(Date.now())},[]);
 useEffect(()=>{if(hydrated)try{localStorage.setItem(CACHE,JSON.stringify(s))}catch{}},[s,hydrated]);
 function sound(long=false){try{navigator.vibrate?.(long?[200,100,200]:80);const c=audio.current;if(c&&c.state==='running'){const o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);g.gain.value=.18;o.frequency.value=long?900:600;o.start();o.stop(c.currentTime+(long?.5:.1));}}catch{}}
 async function prepareAudio(){try{audio.current??=new AudioContext();await audio.current.resume()}catch{}}
 useEffect(()=>{const tick=()=>{const n=Date.now();setNow(n);const prev=current.current;const next=advance(prev,n,document.visibilityState==='visible'&&openRef.current);if(next!==prev){commit(next);if(next.phase==='run')sound(true)}else if(prev.phase==='rest'&&!prev.paused){const left=Math.ceil((prev.anchor+prev.rest*1000-n)/1000);const key=prev.splits.length+':'+left;if(left>0&&left<=3&&cueKey.current!==key){cueKey.current=key;sound()}}};const t=setInterval(tick,100);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(t);document.removeEventListener('visibilitychange',tick)}},[]);
 const moving=s.phase==='run'||s.phase==='rest';
 useEffect(()=>{if(!moving||s.paused||!open)return;let lock:WakeLockSentinel|null=null,cancel=false;const acquire=async()=>{try{if(document.visibilityState==='visible'&&'wakeLock' in navigator){const l=await navigator.wakeLock.request('screen');if(cancel){await l.release();return}lock=l;setAwake(true);l.addEventListener('release',()=>setAwake(false));}}catch{setAwake(false)}};void acquire();document.addEventListener('visibilitychange',acquire);return()=>{cancel=true;document.removeEventListener('visibilitychange',acquire);void lock?.release();setAwake(false)}},[moving,!!s.paused,open]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(['run','rest','ready'].includes(current.current.phase)){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[]);
 function close(){const v=current.current;if(['run','rest'].includes(v.phase)&&!v.paused)commit(togglePause(v,Date.now()));onClose()}
 function start(){void prepareAudio();commit(startLap(current.current,Date.now()));sound(true)}
 function lap(){const n=Date.now(),next=finishLap(current.current,n);if(next!==current.current){commit(next);sound(true)}}
 function reset(){commit({...freshInterval(uid()),rounds:s.rounds,metres:s.metres,rest:s.rest,auto:s.auto});setImported(null);setManual('');setErr('');setConfirm(false)}
 const clockNow=s.paused||now;const clock=s.phase==='run'?Math.max(0,(clockNow-s.anchor)/1000):s.phase==='rest'?Math.max(0,Math.ceil((s.anchor+s.rest*1000-clockNow)/1000)):0;
 const runningTotal=s.splits.reduce((a,b)=>a+b,0);
 function review(values=s.splits,manualEntry=false){onReview({id:manualEntry?uid():s.id,rounds:manualEntry?values.length:s.rounds,metres:manualEntry?importMetres:s.metres,splits:values,recoveries:manualEntry?values.slice(1).map(()=>importRest):s.recoveries,duration:manualEntry?values.reduce((a,b)=>a+b,0)+Math.max(0,values.length-1)*importRest:Math.round(((s.finished||Date.now())-s.started)/1000),date:manualEntry?Date.now():s.started,source:manualEntry?'Imported stopwatch splits; recovery uses the entered duration.':'Stride lap stopwatch; run times exclude recovery and paused time.'});}
 async function file(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.size>100000){setErr('Choose a text or CSV file smaller than 100 KB.');return}const t=await f.text();setManual(t);setImported(null);setErr('');e.target.value=''}
 return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent className="modal interval-modal top-0 left-0 right-0 bottom-0 m-auto translate-none"><DialogHeader><DialogTitle>Run intervals</DialogTitle><DialogDescription>Finish a lap. Tap once. Let Stride time your recovery.</DialogDescription></DialogHeader><Tabs value={mode} onValueChange={setMode}><TabsList className="interval-tabs"><TabsTrigger value="stopwatch">Live stopwatch</TabsTrigger><TabsTrigger value="import" disabled={moving||s.phase==='ready'}>Enter / import splits</TabsTrigger></TabsList>
 <TabsContent value="stopwatch"><div className="interval-runner">
 {s.phase==='idle'&&<><div className="interval-presets">{[4,5,6].map(n=><button className={s.rounds===n&&s.metres===400?'btn':'btn secondary'} key={n} onClick={()=>commit({...s,rounds:n,metres:400,rest:120})}>{n} × 400 m</button>)}<button className={s.metres===2400?'btn':'btn secondary'} onClick={()=>commit({...s,rounds:2,metres:2400,rest:240})}>2 × 2.4 km</button></div>{s.metres===2400&&<p className="tip">Controlled repeats: about 6–7/10 effort. Earlier guide: 14:20–14:50 each; adjust to how you feel. Walk/easy recovery for 3–5 minutes. Tap Lap complete after the full 2.4 km (six track laps).</p>}<div className="form-grid three"><label className="field"><span>Laps</span><input type="number" min="1" max="20" value={s.rounds} onChange={e=>commit({...s,rounds:Math.max(1,Math.min(20,Math.floor(+e.target.value)))})}/></label><label className="field"><span>Metres per lap</span><input type="number" min="50" max="5000" step="50" value={s.metres} onChange={e=>commit({...s,metres:Math.max(50,Math.min(5000,Math.floor(+e.target.value)))})}/></label><label className="field"><span>Recovery (seconds)</span><input type="number" min="5" max="600" value={s.rest} onChange={e=>commit({...s,rest:Math.max(5,Math.min(600,Math.floor(+e.target.value)))})}/></label></div><label className="switch-label"><Switch checked={s.auto} onCheckedChange={v=>commit({...s,auto:v})}/>Start the next lap automatically</label><p className="muted">Warm up first. Tap Lap complete at your marked finish line. This stopwatch does not measure distance.</p><button className="btn interval-main-action" disabled={!hydrated} onClick={start}><Play/>Start first lap</button></>}
 {s.phase!=='idle'&&<><div className={'interval-clock '+(s.phase==='rest'?'is-rest':'')}><span className="eyebrow" role="status">{s.paused?'PAUSED':s.phase==='run'?`RUN · LAP ${s.splits.length+1} OF ${s.rounds}`:s.phase==='rest'?`RECOVER · LAP ${s.splits.length} COMPLETE`:s.phase==='ready'?'READY FOR THE NEXT LAP':s.splits.length===s.rounds?'INTERVALS COMPLETE':'SESSION ENDED'}</span><strong aria-label="Interval time">{s.phase==='done'?time(runningTotal):s.phase==='ready'?'Ready':time(Math.floor(clock))}</strong><span>{s.phase==='done'?`${s.splits.length} laps · ${s.splits.length*s.metres/1000} km of running`:s.phase==='rest'?`${s.auto?'Next lap starts after':'Tap to start after'} recovery`:s.phase==='ready'?'Tap when you are ready to run':`${s.metres} metres per lap`}</span></div>
 {s.phase==='run'&&!s.paused&&<button className="btn interval-main-action" onClick={lap} disabled={clock<1}><Flag/>Lap complete · {s.splits.length+1}/{s.rounds}</button>}
 {s.phase==='rest'&&!s.paused&&<p className="interval-rest-note"><Volume2 size={18}/>Recover now. Watch for the countdown and listen for the start beep.</p>}
 {s.phase==='ready'&&<><p className="muted">Auto-start was off, or the app was away when recovery ended. No new lap has been timed yet.</p><button className="btn interval-main-action" onClick={start}><Play/>Start lap {s.splits.length+1}</button></>}
 {moving&&<div className="button-row"><button className="btn secondary" onClick={()=>{void prepareAudio();commit(togglePause(current.current,Date.now()))}}>{s.paused?<Play size={18}/>:<Pause size={18}/>} {s.paused?'Resume':'Pause'}</button><button className="text-btn" onClick={()=>commit(stopEarly(current.current,Date.now()))}>End session</button></div>}
 {s.phase==='ready'&&<button className="text-btn" onClick={()=>commit(stopEarly(current.current,Date.now()))}>End session</button>}
 {s.phase==='done'&&<><p className="muted">Only completed laps are included. Review and save them to your workout journal. Times are rounded to the nearest second.</p><button className="btn interval-main-action" disabled={!s.splits.length||!canSave} onClick={()=>review()}>Review & save workout</button>{!canSave&&<p className="muted">Sign in to save to your account. Your stopwatch draft stays on this device.</p>}</>}
 </>}
 {s.splits.length>0&&<section className="interval-results"><div className="section-heading"><h3>Your laps</h3><span className="subtle">{time(runningTotal)} running</span></div><ol>{s.splits.map((v,i)=><li key={i}><span>Lap {i+1}<small>{s.metres} m</small></span><b>{time(v)}</b><small>{s.recoveries[i]!==undefined?`${time(Math.round(s.recoveries[i]))} recovery`:'—'}</small></li>)}</ol><p className="muted">Intervals include breaks and do not count as a continuous 2.4 km personal best.</p></section>}
 {s.phase!=='idle'&&<button className="text-btn" onClick={()=>setConfirm(true)}>Start a new interval session</button>}
 <p className="interval-device-note">{awake?'Screen staying awake. ':''}Keep Stride open for reliable cues. If you lock the phone, audio and vibration may stop. Closing this panel pauses the timer. A refreshed running timer restores paused; check its time before resuming.</p>
 </div></TabsContent>
 <TabsContent value="import"><div className="form-stack"><p>Use your phone’s stopwatch, then paste lap times or upload a text / CSV export. No AI key or stopwatch connection needed.</p><div className="form-grid"><label className="field"><span>Metres per lap</span><input type="number" min="50" max="5000" value={importMetres} onChange={e=>setImportMetres(Math.max(50,Math.min(5000,Math.floor(+e.target.value))))}/></label><label className="field"><span>Recovery between laps (seconds)</span><input type="number" min="5" max="600" value={importRest} onChange={e=>setImportRest(Math.max(5,Math.min(600,Math.floor(+e.target.value))))}/></label></div><label className="field"><span>Lap times</span><textarea value={manual} placeholder={'2:12, 2:08, 2:15, 2:11, 2:10, 2:09'} onChange={e=>{setManual(e.target.value);setImported(null)}}/><small>Individual running laps only; leave out recovery laps. CSV format: lap,time.</small></label><label className="switch-label"><Switch checked={cumulative} onCheckedChange={v=>{setCumulative(v);setImported(null)}}/>These are cumulative running times</label><p className="muted">Cumulative times must exclude breaks. For example, 2:10, 4:25 becomes laps of 2:10 and 2:15.</p><div className="button-row"><label className="btn secondary file-btn"><Upload size={18}/>Upload TXT / CSV<input type="file" accept=".txt,.csv,text/plain,text/csv" onChange={e=>void file(e)}/></label><button className="btn" onClick={()=>{try{setImported(parseSplits(manual,cumulative));setErr('')}catch(e){setImported(null);setErr((e as Error).message)}}}>Preview splits</button></div>{err&&<p className="error-text" role="alert">{err}</p>}{imported&&<div className="tip"><h3>{imported.length} × {importMetres} m</h3><p>{imported.map(time).join(' · ')}</p><p>Running total: {time(imported.reduce((a,b)=>a+b,0))}. Recovery is recorded separately.</p><button className="btn" disabled={!canSave} onClick={()=>review(imported,true)}>Review & save workout</button>{!canSave&&<p>Sign in to save imported splits.</p>}</div>}</div></TabsContent></Tabs>
 <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent className="stride-confirm top-0 left-0 right-0 bottom-0 m-auto translate-none"><AlertDialogHeader><AlertDialogTitle>Start fresh?</AlertDialogTitle><AlertDialogDescription>This clears the interval stopwatch draft on this device. Save completed laps first if you want to keep them. Saved workouts stay in your journal.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep this session</AlertDialogCancel><AlertDialogAction onClick={reset}>Clear draft & start fresh</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </DialogContent></Dialog>
}
