'use client';
import {ArrowRight,Check,ChevronRight,Clock3,Footprints,Heart,Play,Plus,Target} from 'lucide-react';
import {today,weekStart,type State,type Session} from '@/lib/data';
export default function MobileHome({s,loaded,completed,goalDays,score,onStart,onPick,onNavigate,onLog,onCheck,onIntervals}:{s:State,loaded:boolean,completed:number,goalDays:number,score:number|null,nextMilestone:number,onStart:(s:Session)=>void,onPick:()=>void,onNavigate:(t:string)=>void,onLog:()=>void,onCheck:()=>void,onIntervals:()=>void}){
const sessions=s.busy?s.plan.sessions.slice(0,2):s.plan.sessions;
const logs=s.workouts.filter(w=>w.date>=weekStart()&&w.date<=today()&&w.status==='complete');
const next=sessions.find(a=>!logs.some(w=>w.sessionId===a.id))??sessions[0];
const checked=s.checkins.find(c=>c.date===today());
const allDone=completed>=sessions.length;
return <div className="today-screen">
<div className="today-greeting"><span className="eyebrow">{new Date(today()+'T00:00:00').toLocaleDateString('en-SG',{weekday:'long',day:'numeric',month:'short'})}</span><h1>Let’s move, {s.profile.name}.</h1><p>A little progress, at your pace.</p></div>
<div className="today-layout"><section className="next-workout"><div className="next-kicker"><span>{allDone?'WEEK COMPLETE · TAKE IT EASY':'YOUR NEXT SESSION'}</span><span><Clock3 size={15}/>{next.minutes} min</span></div><h2>{allDone?'You showed up. Well done.':next.name}</h2><p>{allDone?'Make room for recovery. Your plan is here when you’re ready for another session.':next.description}</p><button className="start-workout" disabled={!loaded} onClick={allDone?()=>onNavigate('My training'):()=>onStart(next)}>{allDone?<Check size={20}/>:<Play size={18} fill="currentColor"/>}{allDone?'View your plan':'Start workout'}<ArrowRight size={20}/></button><button className="choose-workout" onClick={onPick}>Find a different workout<ChevronRight size={16}/></button></section>
<section className="week-overview"><div className="section-heading"><h2>Your week</h2><span>{completed} of {sessions.length}</span></div><div className="week-session-list">{sessions.map((a,i)=>{const done=logs.some(w=>w.sessionId===a.id);return <button key={a.id} onClick={()=>onNavigate('My training')}><span className={'week-step '+(done?'is-done':'')}>{done?<Check size={17}/>:i+1}</span><span><b>{a.name}</b><small>{done?'Completed':`${a.minutes} min · ${a.tag}`}</small></span><ChevronRight size={16}/></button>})}</div><p>Move sessions to fit your week. Rest counts, too.</p></section></div>
<div className="quick-tools"><button onClick={onIntervals}><span className="tool-icon"><Footprints size={23}/></span><span><b>Run intervals</b><small>Laps, rest, repeat</small></span><ChevronRight size={18}/></button><button onClick={onLog} disabled={!loaded}><span className="tool-icon"><Plus size={23}/></span><span><b>Log a workout</b><small>Today or a previous day</small></span><ChevronRight size={18}/></button></div>
<div className="today-bottom"><button className="calm-row" onClick={onCheck} disabled={!loaded}><Heart size={21}/><span><b>{checked?'Today’s check-in':'How are you feeling?'}</b><small>{checked?`${checked.sleep}h sleep · Energy ${checked.energy}/5`:'A quick check-in for your recovery'}</small></span><ChevronRight size={18}/></button><button className="calm-row" onClick={()=>onNavigate('Progress')}><Target size={21}/><span><b>{score===null?`Working towards ${s.profile.target} points`:`${score} / 100 IPPT points`}</b><small>{score===null?'Your first full test starts the story':`Target ${s.profile.target} points`}{goalDays>0?` · ${goalDays} days to go`:''}</small></span><ChevronRight size={18}/></button></div>
</div>}
