'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {guides,micros,seconds,time,today,workoutSchema,type State,type Session,type Workout} from '@/lib/data';
import {strengthVersions,previousDate} from '@/lib/training';
import {checklistRows,changeChecklist,checklistResult,parseRunTime,runSummary,type ChecklistRow} from '@/lib/logging';
import {Plus,X} from 'lucide-react';
function Field({label,children,hint}:{label:string,children:React.ReactNode,hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
type RunRow={distance:string,time:string,rest:string,approximate:boolean};
export default function WorkoutEditor({value,s,saving,onClose,onSave}:{value:Workout,s:State,saving:boolean,onClose:()=>void,onSave:(w:Workout)=>void}){
 const editing=s.workouts.some(a=>a.id===value.id);
 const template=[...strengthVersions,...s.plan.sessions,...micros].find(a=>a.name===value.name)??s.plan.sessions.find(a=>a.id===value.sessionId);
 const [w,setW]=useState(value),[rows,setRows]=useState<ChecklistRow[]>(()=>checklistRows(value,['B','C'].includes(value.sessionId)||value.runType!=='none'?undefined:template)),[chosen,setChosen]=useState(template?.variant?`A:${template.variant}`:template?.id??'custom'),[kind,setKind]=useState(value.runType!=='none'||value.distance>0||['B','C'].includes(value.sessionId)?'run':'strength'),[statusMode,setStatusMode]=useState(value.checklist||!editing&&!value.continuation?'auto':value.status),[autoTitle,setAutoTitle]=useState(!editing),[repeats,setRepeats]=useState(value.runType==='interval'),[err,setErr]=useState('');
 const [lapTimes,setLapTimes]=useState(value.splits.map(time).join(', '));
 const [runs,setRuns]=useState<RunRow[]>(()=>value.runSegments?.length?value.runSegments.map(r=>({distance:String(r.distance),time:time(r.seconds),rest:r.recoveryAfter===null?'':String(r.recoveryAfter),approximate:!!r.recoveryApproximate})):value.runType==='interval'&&value.splits.length>1?value.splits.map(v=>({distance:String(value.distance/value.splits.length),time:time(v),rest:'',approximate:false})):[{distance:value.distance?String(value.distance):'',time:value.seconds?time(value.seconds):'',rest:'',approximate:false}]);
 const update=(key:keyof Workout,v:unknown)=>setW({...w,[key]:v});
 const patch=(index:number,p:Partial<ChecklistRow>)=>setRows(rows.map((r,i)=>i===index?{...r,...p}:r));
 function selectWorkout(key:string){setChosen(key);const session=key.startsWith('A:')?strengthVersions.find(a=>a.variant===key.slice(2)):[...s.plan.sessions,...micros].find(a=>a.id===key);if(session){setRows(['B','C'].includes(session.id)?checklistRows({sets:rows.filter(r=>r.done).flatMap(r=>r.sets)} as Workout):changeChecklist(rows,session));setW({...w,sessionId:session.id,name:session.name});setStatusMode('auto');setKind(['B','C'].includes(session.id)?'run':'strength');}else{setW({...w,sessionId:'custom'});setKind(key==='run'?'run':'strength');}setErr('')}
 function resize(index:number,n:number){if(!Number.isInteger(n)||n<1||n>30)return;const r=rows[index];patch(index,{sets:Array.from({length:n},(_,i)=>r.sets[i]??{exercise:r.exercise,reps:0,unit:r.sets[0]?.unit??'reps',incline:0,rest:0})})}
 function patchRun(i:number,p:Partial<RunRow>){setRuns(runs.map((r,j)=>i===j?{...r,...p}:r))}
 function segments(){return runs.map((r,i)=>({distance:Number(r.distance),seconds:parseRunTime(r.time),recoveryAfter:i===runs.length-1?null:r.rest===''?null:Number(r.rest),recoveryApproximate:r.approximate}))}
 let preview:ReturnType<typeof runSummary>|null=null;try{if(kind==='run')preview=runSummary(segments(),repeats)}catch{}
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setErr('');try{
 const date=String(new FormData(e.currentTarget).get('workoutDate')??w.date);
 if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date+'T00:00:00Z'))||new Date(date+'T00:00:00Z').toISOString().slice(0,10)!==date||date>today())throw Error('Choose a valid date on or before today.');
 const result=checklistResult(statusMode==='skipped'?rows.map(r=>({...r,done:false})):rows);let next:Workout={...w,date,...result,status:statusMode==='auto'?(kind==='run'?'complete':result.status):statusMode as Workout['status']};
 if(next.status==='skipped')next={...next,sets:[],distance:0,seconds:0,splits:[],runSegments:[],runType:'none',testType:'none',pushups:null,situps:null};
 if(kind==='run'&&next.status!=='skipped'){const seg=segments();if(!repeats&&seg.length!==1)throw Error('Use runs with recovery for multiple efforts.');const info=runSummary(seg,repeats);next={...next,distance:info.distance,seconds:info.seconds,runType:repeats?'interval':w.runType==='interval'||w.runType==='none'?'run':w.runType,splits:repeats?info.splits:lapTimes.trim()?lapTimes.split(',').map(parseRunTime):[],runSegments:seg,name:autoTitle?info.name:w.name,sessionId:repeats&&w.sessionId==='custom'?'B':w.sessionId};}
 if(next.testType!=='none'&&(next.runType==='interval'||next.pushups===null||next.situps===null||next.distance!==2.4||next.seconds<=0))throw Error('A full IPPT test needs both timed stations and a continuous 2.4 km run. Choose “none” for training or repeats.');
 next.continuation=next.status==='partial'&&next.sessionId===value.sessionId?next.continuation:undefined;
 const checked=workoutSchema.safeParse(next);if(!checked.success)throw Error('Check your values: '+checked.error.issues[0].message);onSave(checked.data);
 }catch(error){setErr((error as Error).message)}}
 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="modal workout-log top-0 left-0 right-0 bottom-0 m-auto translate-none"><DialogHeader><DialogTitle>{editing?'Edit workout':'Log a past workout'}</DialogTitle><DialogDescription>Choose your workout, tick what you did, and enter your actual results.</DialogDescription></DialogHeader>
 <form className="form-stack" onSubmit={submit}>
 <section className="workout-date"><Field label="Date you trained"><input name="workoutDate" type="date" required max={today()} value={w.date} onInput={e=>update('date',e.currentTarget.value)} onChange={e=>update('date',e.target.value)}/></Field><div className="date-shortcuts"><button type="button" aria-pressed={w.date===today()} onClick={()=>update('date',today())}>Today</button><button type="button" aria-pressed={w.date===previousDate(today())} onClick={()=>update('date',previousDate(today()))}>Yesterday</button></div></section>
 <Field label="Workout to log"><select className="select-control" value={chosen} onChange={e=>selectWorkout(e.target.value)}><option value="custom">Other / custom workout</option><option value="run">Run · name it automatically</option>{strengthVersions.map(a=><option key={a.variant} value={'A:'+a.variant}>A · {a.variant}</option>)}{[...s.plan.sessions,...micros].map(a=><option value={a.id} key={a.id}>{a.id} · {a.name}</option>)}</select></Field>
 {kind==='strength'&&<p className="tip">Tick only what you completed. Unchecked exercises stay out of your recorded sets. You can swap an exercise if you used different equipment.</p>}
 {kind==='run'&&<section className="run-entry"><Field label="How did you run?"><select className="select-control" value={repeats?'repeats':'continuous'} onChange={e=>{const repeat=e.target.value==='repeats';setRepeats(repeat);if(repeat&&runs.length===1)setRuns([...runs,{distance:'',time:'',rest:'',approximate:false}])}}><option value="continuous" disabled={runs.length>1}>One continuous run</option><option value="repeats">Separate runs with recovery</option></select></Field>
 {runs.map((r,i)=><div className="run-entry-row" key={i}><div className="section-heading"><h3>{repeats?`Run ${i+1}`:'Your run'}</h3>{runs.length>1&&<button type="button" className="icon-btn" aria-label={`Remove run ${i+1}`} onClick={()=>setRuns(runs.filter((_,j)=>j!==i))}><X size={16}/></button>}</div><div className="form-grid"><Field label={`Run ${i+1} distance (km)`}><input type="number" inputMode="decimal" min="0.01" max="100" step="0.01" value={r.distance} onChange={e=>patchRun(i,{distance:e.target.value})}/></Field><Field label={`Run ${i+1} time`} hint="Minutes:seconds, e.g. 12:43"><input inputMode="decimal" placeholder="12:43" value={r.time} onChange={e=>patchRun(i,{time:e.target.value})}/></Field>{repeats&&i<runs.length-1&&<><Field label={`Recovery after run ${i+1} (seconds)`} hint="Leave blank if unknown"><input type="number" inputMode="numeric" min="0" max="3600" placeholder="60" value={r.rest} onChange={e=>patchRun(i,{rest:e.target.value})}/></Field><label className="switch-label"><Checkbox checked={r.approximate} onCheckedChange={v=>patchRun(i,{approximate:v===true})}/>About this long</label></>}</div></div>)}
 {repeats&&runs.length<20&&<button className="text-btn" type="button" onClick={()=>setRuns([...runs,{distance:'',time:'',rest:'',approximate:false}])}><Plus size={16}/>Add another run</button>}
 {preview&&<div className="tip" aria-live="polite"><b>{preview.name}</b><p>{preview.distance} km · {time(preview.seconds)} running{preview.elapsed!==null&&repeats?` · ${preview.approximate?'about ':''}${time(preview.elapsed)} including recovery`:''}</p><small>{repeats?'Classified as intervals because you ran separate efforts with recovery. This is not a continuous 2.4 km test.':'Saved as a run. You can specify easy, tempo or a time trial in the details.'}</small></div>}</section>}
 <section className="log-checklist"><div className="section-heading"><h3>{kind==='run'?'Other exercises (optional)':'Your exercise checklist'}</h3><span className="subtle">{rows.filter(r=>r.done).length} of {rows.length} done</span></div>
 {rows.map((r,i)=><div key={r.key} className={'log-exercise '+(r.done?'is-done':'')}><label className="log-exercise-toggle"><Checkbox checked={r.done} aria-label={`Completed ${r.exercise}`} onCheckedChange={v=>patch(i,{done:v===true})}/><span><b>{r.exercise}</b><small>{r.plannedSets?`Planned: ${r.plannedSets} sets · ${r.target}`:'Added exercise'}</small></span></label>
 {r.done&&<div className="log-exercise-body"><Field label={`Exercise ${i+1}`}><input list="log-exercise-names" value={r.exercise} onChange={e=>patch(i,{exercise:e.target.value})} required/></Field><div className="form-grid"><Field label={`Completed sets for ${r.exercise}`}><input type="number" min="1" max="30" value={r.sets.length} onChange={e=>resize(i,+e.target.value)}/></Field><Field label={`Amount per set for ${r.exercise}`} hint="Fills all sets; expand below for different amounts"><input type="number" inputMode="decimal" min="0" max="10000" placeholder="e.g. 10" value={r.sets.every(a=>a.reps===r.sets[0]?.reps)?r.sets[0]?.reps||'':''} onChange={e=>patch(i,{sets:r.sets.map(a=>({...a,reps:+e.target.value}))})}/></Field><Field label={`Unit for ${r.exercise}`}><select className="select-control" value={r.sets[0]?.unit??'reps'} onChange={e=>patch(i,{sets:r.sets.map(a=>({...a,unit:e.target.value as 'reps'}))})}><option>reps</option><option>seconds</option><option>metres</option></select></Field><Field label={`Weight for ${r.exercise} (kg)`} hint={/dumbbell/i.test(r.exercise)?'Per dumbbell · optional':'Optional'}><input type="number" min="0" max="1000" step="0.5" placeholder="Not recorded" value={r.sets.every(a=>a.weight===r.sets[0]?.weight)?r.sets[0]?.weight??'':''} onChange={e=>patch(i,{sets:r.sets.map(a=>({...a,weight:e.target.value===''?undefined:+e.target.value}))})}/></Field></div>
 <details><summary>Individual sets & extra details</summary>{r.sets.map((a,j)=><div className="log-set" key={j}><b>Set {j+1}</b><div className="form-grid"><Field label={`Set ${j+1} amount for ${r.exercise}`}><input type="number" min="0" max="10000" step="any" value={a.reps||''} onChange={e=>patch(i,{sets:r.sets.map((x,k)=>k===j?{...x,reps:+e.target.value}:x)})}/></Field><Field label={`Set ${j+1} weight for ${r.exercise}`}><input type="number" min="0" max="1000" step="0.5" value={a.weight??''} onChange={e=>patch(i,{sets:r.sets.map((x,k)=>k===j?{...x,weight:e.target.value===''?undefined:+e.target.value}:x)})}/></Field><Field label="Incline height (cm)"><input type="number" min="0" max="250" value={a.incline} onChange={e=>patch(i,{sets:r.sets.map((x,k)=>k===j?{...x,incline:+e.target.value}:x)})}/></Field><Field label="Rest (seconds)"><input type="number" min="0" max="3600" value={a.rest||''} onChange={e=>patch(i,{sets:r.sets.map((x,k)=>k===j?{...x,rest:+e.target.value}:x)})}/></Field><Field label="Location"><select className="select-control" value={a.location??''} onChange={e=>patch(i,{sets:r.sets.map((x,k)=>k===j?{...x,location:(e.target.value||undefined) as 'Gym'|'Home'|undefined}:x)})}><option value="">Not specified</option><option>Gym</option><option>Home</option></select></Field></div></div>)}</details></div>}</div>)}
 <button className="text-btn" type="button" onClick={()=>setRows([...rows,{key:crypto.randomUUID(),exercise:'Other exercise',plannedSets:0,target:'',done:true,sets:[{exercise:'Other exercise',reps:0,unit:'reps',incline:0,rest:0}]}])}><Plus size={16}/>Add an exercise</button><datalist id="log-exercise-names">{guides.map(g=><option key={g.name} value={g.name}/>)}</datalist></section>
 <details className="logging-details"><summary>Workout details & test results</summary><div className="form-stack">{kind==='run'&&<label className="switch-label"><Checkbox checked={autoTitle} onCheckedChange={v=>setAutoTitle(v===true)}/>Name this run automatically</label>}<Field label="Workout title"><input required value={kind==='run'&&autoTitle?(preview?.name??'Run'):w.name} disabled={kind==='run'&&autoTitle} onChange={e=>update('name',e.target.value)}/></Field><div className="form-grid"><Field label="Completion"><select className="select-control" value={statusMode} onChange={e=>setStatusMode(e.target.value)}><option value="auto">Automatic from checklist</option><option value="complete">Complete</option><option value="partial">Partial</option><option value="skipped">Skipped</option></select></Field><Field label="Duration (minutes)"><input type="number" min="0" max="600" placeholder="Not recorded" value={w.minutes??''} onChange={e=>update('minutes',e.target.value===''?null:+e.target.value)}/></Field><Field label="Effort (0–10)"><input type="number" min="0" max="10" placeholder="Not recorded" value={w.effort??''} onChange={e=>update('effort',e.target.value===''?null:+e.target.value)}/></Field>{kind==='run'&&!repeats&&<Field label="Run type"><select className="select-control" value={w.runType==='none'||w.runType==='interval'?'run':w.runType} onChange={e=>update('runType',e.target.value)}><option value="run">Run (unspecified effort)</option><option>easy</option><option>tempo</option><option>time trial</option></select></Field>}</div>
 {kind==='run'&&!repeats&&<Field label="Continuous-run lap times" hint="Optional, separated by commas. These are laps without recovery breaks."><input value={lapTimes} onChange={e=>setLapTimes(e.target.value)} placeholder="2:10, 2:15"/></Field>}<h3>One-minute station results</h3><p className="muted">Only enter valid timed counts. Ordinary training sets stay in the checklist.</p><div className="form-grid"><Field label="Standard push-ups"><input type="number" min="0" max="200" value={w.pushups??''} onChange={e=>update('pushups',e.target.value===''?null:+e.target.value)}/></Field><Field label="Sit-ups"><input type="number" min="0" max="200" value={w.situps??''} onChange={e=>update('situps',e.target.value===''?null:+e.target.value)}/></Field><Field label="Full IPPT test"><select className="select-control" value={w.testType} onChange={e=>update('testType',e.target.value)}><option>none</option><option>practice</option><option>mock</option><option>official</option></select></Field></div></div></details>
 {w.continuation&&<p className="tip">Keep completion set to partial if you want to resume the guided session later.</p>}<Field label="Notes"><textarea value={w.notes} onChange={e=>update('notes',e.target.value)}/></Field>
 {statusMode==='auto'&&kind==='strength'&&<p className="muted">{rows.filter(r=>r.done).length===0?'No exercises selected yet.':rows.some(r=>r.plannedSets>0&&(!r.done||r.sets.length<r.plannedSets))?'Will save as partial — only checked exercises are counted.':'Will save as complete.'}</p>}
 {err&&<p className="error-text" role="alert">{err}</p>}<div className="modal-footer"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button type="submit" className="btn" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Save workout'}</button></div></form></DialogContent></Dialog>
}
